{"name": "创建轨迹", "status": "failed", "statusDetails": {"message": "AssertionError: assert 21120 == 0\n  +21120\n  -0", "trace": "self = <API_test.test_case.TestCase object at 0x0000020B06B0ADA0>\n\n    @allure.feature(\"轨迹\")\n    @allure.title(\"创建轨迹\")\n    @pytest.mark.测试\n    def test_creattrack(self):\n    \n        r = self.track.creat_track()\n    \n>       assert r[\"errcode\"] == 0\nE       assert 21120 == 0\nE         +21120\nE         -0\n\ntest_case.py:26: AssertionError"}, "start": 1652933109555, "stop": 1652933109637, "uuid": "c64e0bd9-b4f3-49c4-a989-c77d33bbb9a2", "historyId": "0cf908cb910b1aaa8e07150b8bee8cc3", "testCaseId": "365ec04469551cf0e3dc5955ab99b8ff", "fullName": "test_case.TestCase#test_creattrack", "labels": [{"name": "feature", "value": "轨迹"}, {"name": "tag", "value": "测试"}, {"name": "suite", "value": "test_case"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "BJI000-L26S8DL3"}, {"name": "thread", "value": "32360-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case"}]}